---
- name: enable repos
  template:
    src: files/open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644
- name: install tomcat
  package:
    name: tomcat
    state: latest
- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes
- name: create ansible and ROOT directories for tomcat
  file:
    path: "{{item}}"
    state: directory
  loop:
    - /usr/share/tomcat/webapps/ROOT
    - /usr/share/tomcat/webapps/ansible
- name: copy static index.html to tomcat webapps/ROOT/index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
- name: copy index.html to tomcat webapps/ansible/index.html
  template:
    src: templates/index.html.ansible.j2
    dest: /usr/share/tomcat/webapps/ansible/index.html
- name: start tomcat
  service:
    name: tomcat
    state: started
- name: install apache
  yum:
    name: httpd
    state: latest
- name: enable and start apache
  service:
    name: httpd
    state: started
    enabled: yes
